name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - id: Build-Vue
      run: |
            yarn install
            cd vuelearnone/vuelearnone
            yarn build
            cd dist
            git init
            git add -A
            git commit -m 'deploy'
            git push -f https://Hlautameki:${{ secrets.GITHUB_TOKEN }}@github.com/Hlautameki/vuelearnone.git master:gh-pages
      shell: bash
